# Generated by Django 5.2.12 on 2026-04-04 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_sessions', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeTraversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traversed_at', models.DateTimeField(auto_now_add=True)),
                ('from_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traversals_from', to='tweets.tweetnode')),
                ('to_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traversals_to', to='tweets.tweetnode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_traversals', to='graphs.graphsession')),
            ],
        ),
        migrations.CreateModel(
            name='NodeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('dwell_seconds', models.PositiveIntegerField(default=0)),
                ('position_in_path', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_visits', to='graphs.graphsession')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tweets.tweetnode')),
            ],
            options={
                'ordering': ['position_in_path'],
            },
        ),
        migrations.CreateModel(
            name='UserGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('created', 'Created'), ('pinned', 'Pinned'), ('seeded', 'Seeded')], max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='graphs.usergraph')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='tweets.tweetnode')),
            ],
            options={
                'unique_together': {('graph', 'tweet')},
            },
        ),
        migrations.CreateModel(
            name='UserGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='graphs.usergraph')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='graphs.usergraphnode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='graphs.usergraphnode')),
            ],
            options={
                'unique_together': {('graph', 'source_node', 'target_node')},
            },
        ),
    ]
