# Generated by Django 5.2.12 on 2026-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergraph',
            name='anchor_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergraph',
            name='cached_anchor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergraph',
            name='cached_total_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
